FROM alpine:edge

ARG XPUBKEYS
ARG SIGS

ENV XPUBKEYS ${XPUBKEYS}
ENV SIGS ${SIGS}

COPY api_tool.py /api_tool.py
COPY url.key /url.key

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    apk --no-cache update && \
    apk --no-cache add py-m2crypto ca-certificates

ENTRYPOINT ["python", "/api_tool.py"]
